packages:
  - src/miniprogram
  - src/backend
  - src/backstage
  - src/ar_h5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tarojs/binding'
  - '@tarojs/cli'
  - core-js
  - core-js-pure
  - esbuild
  - sharp
